#!/bin/bash

if cat /proc/1/cgroup | tail -1 | grep -q "container"; then
  echo "linux container. Floflis' firstboot won't run."
else
  full_fs=$(df ~ | tail -1 | awk '{print $1;}')  # /dev/sda1
  fs=$(basename $full_fs)                        # sda1
  if grep -q "$fs" /proc/partitions; then
    echo "regular linux install. Floflis' firstboot will proceed."
    FLAG="/var/log/firstboot.log"
    if [ ! -f $FLAG ]
       then
          #Put here your initialization cmds
          echo "This is the first boot."
          cd /home
          for D in `find . -mindepth 1 -maxdepth 1 -type d`
          do
             mkdir .config
             mkdir .config/autostart
             cd
done
          #the next line creates an empty file so it won't run the next boot
          touch $FLAG
       else
          echo "No need to run Floflis' first boot script."
          #task: remove this script from init.d
fi
  else
    echo "live OS running from RAM. Floflis' firstboot won't run."
  fi
fi
