#!/bin/sh
### BEGIN INIT INFO
# Provides: firstboot
# Required-Start:    $local_fs $syslog $remote_fs dbus
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start firstboot script
### END INIT INFO

if cat /proc/1/cgroup | tail -1 | grep -q "container"; then
  echo "linux container. Floflis' firstboot won't run."
else
  full_fs=$(df ~ | tail -1 | awk '{print $1;}')  # /dev/sda1
  fs=$(basename $full_fs)                        # sda1
  if grep -q "$fs" /proc/partitions; then
    echo "regular linux install. Floflis' firstboot will proceed."
    FLAG="/var/log/firstboot.log"
    if [ ! -f $FLAG ]
       then
          #Put here your initialization cmds
          echo "This is the first boot."
          cd /home
          for D in `find . -mindepth 1 -maxdepth 1 -type d`
          do
             cd ${D}
             sudo mv /usr/lib/floflis/layers/core/firstlogon.sh /home
             sudo mv /usr/lib/floflis/layers/core/firstlogonroot.sh /home
             sudo chmod +x /home/firstlogon.sh
             sudo chmod +x /home/firstlogonroot.sh
             mkdir .config
             mkdir .config/autostart
             cd .config/autostart
             cat > firstlogon.sh << ENDOFFILE
[Desktop Entry]
Type=Application
Exec=gnome-terminal --tab --title="Welcome to Floflis!" -- /bin/sh -c 'cd /home; sudo sh ./firstlogon.sh; exec bash'
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=FirstLogon
Name=FirstLogon
Comment[en_US]=
Comment=
Icon=utilities-terminal
StartupNotify=true
Terminal=false

ENDOFFILE
             sudo chmod -R a+rwX .config/autostart && sudo chown ${D//./}:${D//./} .config/autostart
             sudo chown ${D//./}:${D//./} .local/share/gvfs-metadata/home*
             sudo chmod +x firstlogon.sh
             sudo chown ${D//./}:${D//./} .config/autostart/firstlogon.sh
             cd .config/autostart
             sudo mv firstlogon.sh firstlogon.desktop
             sudo chown ${D//./}:${D//./} firstlogon.desktop
             cd ..
             cd ..
             echo "- Cleanning install..."
             sudo rm -rf .config/autostart/firstlogon.sh
             sudo rm -rf /usr/lib/floflis/layers/core/firstlogon.sh
             sudo rm -rf /usr/lib/floflis/layers/core/firstlogonroot.sh
             #sudo rm -rf /etc/init.d/firstboot
             sudo chmod -R a+rwX ${D} && sudo chown ${D//./}:${D//./} ${D}
done
          cd
          #the next line creates an empty file so it won't run the next boot
          touch $FLAG
       else
          echo "No need to run Floflis' first boot script."
          #task: remove this script from init.d
fi
  else
    echo "live OS running from RAM. Floflis' firstboot won't run."
  fi
fi
