#!/bin/bash

# load definitions & settings ---->
if [[ $(echo $PREFIX | grep -o "com.termux") == "com.termux" ]];
then
. /data/data/com.termux/files/usr/lib/floflis/./config
else
. /usr/lib/floflis/./config
fi
export FLOPREFIX
export flofmach && export flofdistro && export flofarch && export osfullname && export osname && export osversion && export osbuild && export osbuildcodename && export updatepatch && export year && export layer && export nxtlayer && export distrobase && export user && export specialbuildattempt
# <---- load definitions & settings

# load modules
# -
if [ -e "$FLOPREFIX"usr/lib/floflis/layers/core/modules ]
then
    . "$FLOPREFIX"usr/lib/floflis/layers/core/./modules.sh
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   echo "Settings:"
   echo "   floflis settings            Opens CLI settings"
   echo "   floflis central             Opens exclusive settings specifially for Floflis"
fi

if [ "$1" = "settings" ]; then
   antiX-cli-cc
fi

if [ "$1" = "central" ]; then
   floflis-central
fi
